version: '3'

services:
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ./target:/src
    depends_on:
      - db